import type { Diagnostic, DocumentSnapshot } from '../documents/types.ts';
import type { Metadata } from './metadata.ts';
import { metadataYaml, projectionMetadata } from './projection-metadata.ts';

/** Bump whenever generated bytes or metadata admission semantics change. */
export const PROJECTION_VERSION = '1';
export const QMD_BUILD = '04e4dbd8245c527a88f1a8f0bda547aef9ca81fb';

export interface DocumentProjection {
  /** Absent when QMD cannot represent the mandatory original source identity. */
  readonly content: string | undefined;
  readonly metadata: Metadata;
  readonly diagnostics: readonly Diagnostic[];
}

/** Keep source body bytes unchanged and replace only authored frontmatter. */
export function projectDocument(
  snapshot: DocumentSnapshot
): DocumentProjection {
  const { metadata, diagnostics } = projectionMetadata(snapshot.document);
  const body = snapshot.source.slice(
    snapshot.document.body.start,
    snapshot.document.body.end
  );
  const content =
    metadata['source_path'] === undefined
      ? undefined
      : `---\n${metadataYaml(metadata)}---\n${body}`;
  return { content, metadata, diagnostics };
}
